/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yyf_shadowsocks_jni_System */

#ifndef _Included_yyf_shadowsocks_jni_System
#define _Included_yyf_shadowsocks_jni_System
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yyf_shadowsocks_jni_System
 * Method:    exec
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_yyf_shadowsocks_jni_System_exec
  (JNIEnv *, jclass, jstring);

/*
 * Class:     yyf_shadowsocks_jni_System
 * Method:    getABI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_yyf_shadowsocks_jni_System_getABI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
